<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="LinksVerification-Suite" duration-ms="17329" started-at="2018-04-12T16:23:12Z" finished-at="2018-04-12T16:23:29Z">
    <groups>
    </groups>
    <test name="LinksVerification-Test" duration-ms="17329" started-at="2018-04-12T16:23:12Z" finished-at="2018-04-12T16:23:29Z">
      <class name="com.packt.tests.LinksVerificationTest">
        <test-method status="PASS" signature="setUp(java.lang.String, org.testng.ITestContext)[pri:0, instance:com.packt.tests.LinksVerificationTest@eafc191]" name="setUp" is-config="true" duration-ms="1112" started-at="2018-04-12T16:23:12Z" finished-at="2018-04-12T16:23:13Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@1d470d0]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="linksVerificationTest()[pri:0, instance:com.packt.tests.LinksVerificationTest@eafc191]" name="linksVerificationTest" duration-ms="16127" started-at="2018-04-12T16:23:13Z" finished-at="2018-04-12T16:23:29Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Response code for 'Basic Auth' [http://the-internet.herokuapp.com/basic_auth] is not 200. It is: 401 code with message: 'Unauthorized' expected [true] but found [false],
Response code for 'Secure File Download' [http://the-internet.herokuapp.com/download_secure] is not 200. It is: 401 code with message: 'Unauthorized' expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Response code for 'Basic Auth' [http://the-internet.herokuapp.com/basic_auth] is not 200. It is: 401 code with message: 'Unauthorized' expected [true] but found [false],
Response code for 'Secure File Download' [http://the-internet.herokuapp.com/download_secure] is not 200. It is: 401 code with message: 'Unauthorized' expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.packt.tests.LinksVerificationTest.linksVerificationTest(LinksVerificationTest.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- linksVerificationTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.packt.tests.LinksVerificationTest@eafc191]" name="tearDown" is-config="true" duration-ms="72" started-at="2018-04-12T16:23:29Z" finished-at="2018-04-12T16:23:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.packt.tests.LinksVerificationTest -->
    </test> <!-- LinksVerification-Test -->
  </suite> <!-- LinksVerification-Suite -->
</testng-results>
