<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="7" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Big Suite" duration-ms="77157" started-at="2018-03-31T17:57:48Z" finished-at="2018-03-31T17:59:06Z">
    <groups>
    </groups>
    <test name="FirstTest" duration-ms="26929" started-at="2018-03-31T17:57:48Z" finished-at="2018-03-31T17:58:15Z">
      <class name="com.packt.tests.FirstTest">
        <test-method status="PASS" signature="setUp(java.lang.String, org.testng.ITestContext)[pri:0, instance:com.packt.tests.FirstTest@6d4b1c02]" name="setUp" is-config="true" duration-ms="4996" started-at="2018-03-31T17:57:49Z" finished-at="2018-03-31T17:57:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@5f0e9815]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="firstTest(java.lang.String, java.lang.String)[pri:0, instance:com.packt.tests.FirstTest@6d4b1c02]" name="firstTest" duration-ms="5352" started-at="2018-03-31T17:57:54Z" finished-at="2018-03-31T17:57:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[tomsmith]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[SuperSecretPassword!]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Page source doesn't contain expected text: You logged into a secure area!Brake expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Page source doesn't contain expected text: You logged into a secure area!Brake expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.packt.tests.FirstTest.firstTest(FirstTest.java:42)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- firstTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.packt.tests.FirstTest@6d4b1c02]" name="tearDown" is-config="true" duration-ms="733" started-at="2018-03-31T17:57:59Z" finished-at="2018-03-31T17:58:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp(java.lang.String, org.testng.ITestContext)[pri:0, instance:com.packt.tests.FirstTest@6d4b1c02]" name="setUp" is-config="true" duration-ms="3510" started-at="2018-03-31T17:58:00Z" finished-at="2018-03-31T17:58:03Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@5f0e9815]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="negativeLogInTest(java.util.Map)[pri:0, instance:com.packt.tests.FirstTest@6d4b1c02]" name="negativeLogInTest" duration-ms="3818" started-at="2018-03-31T17:58:03Z" data-provider="CsvDataProvider" finished-at="2018-03-31T17:58:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=1, password=SuperSecretPassword!, expectedError=Your username is invalid!, username=IncorrectUsername}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- negativeLogInTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.packt.tests.FirstTest@6d4b1c02]" name="tearDown" is-config="true" duration-ms="704" started-at="2018-03-31T17:58:07Z" finished-at="2018-03-31T17:58:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp(java.lang.String, org.testng.ITestContext)[pri:0, instance:com.packt.tests.FirstTest@6d4b1c02]" name="setUp" is-config="true" duration-ms="3495" started-at="2018-03-31T17:58:08Z" finished-at="2018-03-31T17:58:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@5f0e9815]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="negativeLogInTest(java.util.Map)[pri:0, instance:com.packt.tests.FirstTest@6d4b1c02]" name="negativeLogInTest" duration-ms="3548" started-at="2018-03-31T17:58:11Z" data-provider="CsvDataProvider" finished-at="2018-03-31T17:58:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=2, password=IncorrectPassword, expectedError=Your password is invalid!Broken, username=tomsmith}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Actual and expected error messages are different. 
Expected: Your password is invalid!Broken 
Actual: Your password is invalid!
× expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Actual and expected error messages are different. 
Expected: Your password is invalid!Broken 
Actual: Your password is invalid!
× expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.packt.tests.FirstTest.negativeLogInTest(FirstTest.java:61)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- negativeLogInTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.packt.tests.FirstTest@6d4b1c02]" name="tearDown" is-config="true" duration-ms="714" started-at="2018-03-31T17:58:15Z" finished-at="2018-03-31T17:58:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.packt.tests.FirstTest -->
    </test> <!-- FirstTest -->
    <test name="Troubleshooting" duration-ms="50170" started-at="2018-03-31T17:58:15Z" finished-at="2018-03-31T17:59:06Z">
      <class name="com.packt.tests.Troubleshooting">
        <test-method status="PASS" signature="setUp(java.lang.String, org.testng.ITestContext)[pri:0, instance:com.packt.tests.Troubleshooting@1ce92674]" name="setUp" is-config="true" duration-ms="3717" started-at="2018-03-31T17:58:15Z" finished-at="2018-03-31T17:58:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@76884e4b]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="otherTest()[pri:0, instance:com.packt.tests.Troubleshooting@1ce92674]" name="otherTest" duration-ms="10964" started-at="2018-03-31T17:58:19Z" finished-at="2018-03-31T17:58:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- otherTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.packt.tests.Troubleshooting@1ce92674]" name="tearDown" is-config="true" duration-ms="734" started-at="2018-03-31T17:58:30Z" finished-at="2018-03-31T17:58:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp(java.lang.String, org.testng.ITestContext)[pri:0, instance:com.packt.tests.Troubleshooting@1ce92674]" name="setUp" is-config="true" duration-ms="3390" started-at="2018-03-31T17:58:31Z" finished-at="2018-03-31T17:58:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@76884e4b]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="staleElementTest()[pri:0, instance:com.packt.tests.Troubleshooting@1ce92674]" name="staleElementTest" duration-ms="5228" started-at="2018-03-31T17:58:34Z" finished-at="2018-03-31T17:58:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- staleElementTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.packt.tests.Troubleshooting@1ce92674]" name="tearDown" is-config="true" duration-ms="735" started-at="2018-03-31T17:58:40Z" finished-at="2018-03-31T17:58:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp(java.lang.String, org.testng.ITestContext)[pri:0, instance:com.packt.tests.Troubleshooting@1ce92674]" name="setUp" is-config="true" duration-ms="3607" started-at="2018-03-31T17:58:40Z" finished-at="2018-03-31T17:58:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@76884e4b]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="visibilityTest()[pri:0, instance:com.packt.tests.Troubleshooting@1ce92674]" name="visibilityTest" duration-ms="8732" started-at="2018-03-31T17:58:44Z" finished-at="2018-03-31T17:58:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- visibilityTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.packt.tests.Troubleshooting@1ce92674]" name="tearDown" is-config="true" duration-ms="695" started-at="2018-03-31T17:58:53Z" finished-at="2018-03-31T17:58:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp(java.lang.String, org.testng.ITestContext)[pri:0, instance:com.packt.tests.Troubleshooting@1ce92674]" name="setUp" is-config="true" duration-ms="3548" started-at="2018-03-31T17:58:53Z" finished-at="2018-03-31T17:58:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@76884e4b]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="waitTest()[pri:0, instance:com.packt.tests.Troubleshooting@1ce92674]" name="waitTest" duration-ms="8084" started-at="2018-03-31T17:58:57Z" finished-at="2018-03-31T17:59:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA['Good bye World! text is not present on the page.' expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 'Good bye World! text is not present on the page.' expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.packt.tests.Troubleshooting.waitTest(Troubleshooting.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- waitTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.packt.tests.Troubleshooting@1ce92674]" name="tearDown" is-config="true" duration-ms="723" started-at="2018-03-31T17:59:05Z" finished-at="2018-03-31T17:59:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.packt.tests.Troubleshooting -->
    </test> <!-- Troubleshooting -->
  </suite> <!-- Big Suite -->
</testng-results>
